# Configuration for mkdocs

site_name: the.dusktreader blog
site_url: http://blog.dusktreader.dev
repo_url: https://github.com/dusktreader/blog
docs_dir: source
theme:
  name: material
  font:
    code: Fira Code
  features:
    - navigation.instant
    - navigation.expand
    - navigation.footer
    - navigation.tracking
    - navigation.footer
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "blue grey"
      accent: "blue"
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "grey"
      accent: "deep orange"
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
watch:
  - ../docs/source
  - mkdocs.yaml
plugins:
  blog:
    blog_dir: .
    authors_file: .authors.yaml
  tags:
  rss:
    enabled: !ENV [CI, false]
    match_path: source/posts/.*
    date_from_meta:
      as_creation: date
    categories:
      - categories
      - tags
  search:
    lang: en
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - pymdownx.superfences:
  - pymdownx.details:
  - admonition:
  - attr_list:
